# site properties and page defaults
title: "木藤研究室 / Kidou Lab - 名古屋市立大学"
subtitle: "植物生命科学 / Plant Physiology and Molecular Biology"
show-title: false
show-subtitle: false
description: "遺伝子やタンパク質の機能解析を通じて、あなたも美しい生命現象の謎解きに参加しませんか？ | Join us in unraveling the beautiful mysteries of life phenomena through the functional analysis of genes and proteins."
header: images/background.jpg
footer: images/background.jpg
proofer: false
timezone: Asia/Tokyo
future: true

# site social media and other links
links:
  email: kidou@nsc.nagoya-cu.ac.jp
  home-page: https://www.nagoya-cu.ac.jp/nsc/
  address: https://maps.app.goo.gl/DnnSDxsd6jG2uGi39
  external: https://f-arriel.github.io/kidou-lab/admin

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  #hidden gallery  
  gallery:
    output: false

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
